## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file Template.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_12 = Integer(12); _sage_const_10 = Integer(10); _sage_const_13 = Integer(13); _sage_const_0 = Integer(0); _sage_const_8 = Integer(8); _sage_const_235 = Integer(235); _sage_const_1 = Integer(1); _sage_const_17 = Integer(17); _sage_const_34 = Integer(34); _sage_const_5 = Integer(5); _sage_const_238 = Integer(238); _sage_const_241 = Integer(241); _sage_const_11 = Integer(11)## This file (Template.sagetex.sage) was *autogenerated* from Template.tex with sagetex.sty version 2019/11/14 v3.4.
import sagetex
_st_ = sagetex.SageTeXProcessor('Template', version='2019/11/14 v3.4', version_check=False)
_st_.current_tex_line = _sage_const_7 
_st_.blockbegin()
try:
 var("x y z")
 f = -_sage_const_2 *y**_sage_const_2  + _sage_const_4 *y*z - _sage_const_3 *z**_sage_const_2  + _sage_const_4 *y + _sage_const_4 *z - _sage_const_12 
except:
 _st_.goboom(_sage_const_10 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_13 
 _st_.plot(_sage_const_0 , format='png', _p_=implicit_plot3d(f, (x, _sage_const_0 , _sage_const_8 ), (y, _sage_const_0 , _sage_const_8 ), (z, _sage_const_0 , _sage_const_8 )))
except:
 _st_.goboom(_sage_const_13 )
_st_.current_tex_line = _sage_const_235 
_st_.blockbegin()
try:
 g1 = sqrt(_sage_const_1 /_sage_const_2  + sqrt(_sage_const_17 )/_sage_const_34 )*x - (sqrt(_sage_const_1 /_sage_const_2  - sqrt(_sage_const_17 )/_sage_const_34 ))*y + _sage_const_5 
 g2 = sqrt(_sage_const_1 /_sage_const_2  - sqrt(_sage_const_17 )/_sage_const_34 )*x + (sqrt(_sage_const_1 /_sage_const_2  + sqrt(_sage_const_17 )/_sage_const_34 ))*y + _sage_const_4 
except:
 _st_.goboom(_sage_const_238 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_241 
 _st_.plot(_sage_const_1 , format='notprovided', _p_=implicit_plot3d(f.subs({y: g1, z: g2}), (x, -_sage_const_5 , _sage_const_5 ), (y, -_sage_const_5 , _sage_const_5 ), (z, _sage_const_0 , _sage_const_11 )))
except:
 _st_.goboom(_sage_const_241 )
_st_.endofdoc()

